# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rhizome < Formula
  desc "Self-hosted tunnel client — expose local ports via secure tunnels"
  homepage "https://tunnel.springthrough.com"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.5.0/rhizome_darwin_amd64.tar.gz"
      sha256 "303444c0a785fee1627bd2938bd6d83a9ad99d110dc53e54d1ebb4852e251133"

      define_method(:install) do
        bin.install "rhizome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.5.0/rhizome_darwin_arm64.tar.gz"
      sha256 "925be353e29aa1c2d34ae0000ffb6c4f10981b190a516823db9d7a44962e620c"

      define_method(:install) do
        bin.install "rhizome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.5.0/rhizome_linux_amd64.tar.gz"
      sha256 "0988c5bd42be97adbf2e964aaba13c91f1d35a99fc3842b1eb65e9228ff4787a"
      define_method(:install) do
        bin.install "rhizome"
      end
    end
  end

  def caveats
    <<~EOS
      To run rhizome as a background service that survives logout and reboot:

        rhizome service install <port> [--subdomain <name>]

      Before `brew uninstall rhizome`, remove the service first:

        rhizome service uninstall

      Homebrew does not stop launchd services on uninstall, so skipping this
      step leaves a stale plist at ~/Library/LaunchAgents/com.brutalsystems.rhizome.plist
      that will fail to start after the binary is gone.
    EOS
  end

  test do
    system "#{bin}/rhizome", "--help"
  end
end
