# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rhizome < Formula
  desc "Self-hosted tunnel client — expose local ports via secure tunnels"
  homepage "https://tunnel.springthrough.com"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.4.2/rhizome_darwin_amd64.tar.gz"
      sha256 "90cba70822ffd369e0920e6b3d352116e97c5e9e70ffb025911011216e053095"

      define_method(:install) do
        bin.install "rhizome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.4.2/rhizome_darwin_arm64.tar.gz"
      sha256 "26ea0a0f0855a39d921aa407193ef545e372f0d468523551fa923ede58e62320"

      define_method(:install) do
        bin.install "rhizome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.4.2/rhizome_linux_amd64.tar.gz"
      sha256 "c9b293875bfe3b281e64b4d85aaf47f35793658187ef893b73a2804b51057abd"
      define_method(:install) do
        bin.install "rhizome"
      end
    end
  end

  def caveats
    <<~EOS
      To run rhizome as a background service that survives logout and reboot:

        rhizome service install <port> [--subdomain <name>]

      Before `brew uninstall rhizome`, remove the service first:

        rhizome service uninstall

      Homebrew does not stop launchd services on uninstall, so skipping this
      step leaves a stale plist at ~/Library/LaunchAgents/com.brutalsystems.rhizome.plist
      that will fail to start after the binary is gone.
    EOS
  end

  test do
    system "#{bin}/rhizome", "--help"
  end
end
