# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rhizome < Formula
  desc "Self-hosted tunnel client — expose local ports via secure tunnels"
  homepage "https://tunnel.springthrough.com"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.4.3/rhizome_darwin_amd64.tar.gz"
      sha256 "d28051d8faa24cd8704e0b32f2d2d59a928bb13ae05b4b91be00dba03aaea1ab"

      define_method(:install) do
        bin.install "rhizome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.4.3/rhizome_darwin_arm64.tar.gz"
      sha256 "d19b2058392f3b4c30524c4acb1b7d0da169236060ae87f007b801bfbac52bb8"

      define_method(:install) do
        bin.install "rhizome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brutalsystems/homebrew-rhizome/releases/download/v0.4.3/rhizome_linux_amd64.tar.gz"
      sha256 "7ecbd68cb61c8c8d62da3a0effab48dfdd923daded9ffa60156fcb7292e5bd45"
      define_method(:install) do
        bin.install "rhizome"
      end
    end
  end

  def caveats
    <<~EOS
      To run rhizome as a background service that survives logout and reboot:

        rhizome service install <port> [--subdomain <name>]

      Before `brew uninstall rhizome`, remove the service first:

        rhizome service uninstall

      Homebrew does not stop launchd services on uninstall, so skipping this
      step leaves a stale plist at ~/Library/LaunchAgents/com.brutalsystems.rhizome.plist
      that will fail to start after the binary is gone.
    EOS
  end

  test do
    system "#{bin}/rhizome", "--help"
  end
end
